{{- if .Values.prometheus.monitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "azure-resourcegraph-exporter.fullname" . }}
  namespace: {{ template "azure-resourcegraph-exporter.namespace" . }}
  labels: {{ include "azure-resourcegraph-exporter.labels" . | nindent 4 }}
spec:
  jobLabel: {{ default "app.kubernetes.io/name" .Values.prometheus.monitor.jobLabel }}
  {{- include "servicemonitor.scrapeLimits" .Values.prometheus.monitor | nindent 2 }}
  selector:
    matchLabels: {{- include "azure-resourcegraph-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.portName }}
      scheme: {{ .Values.prometheus.monitor.scheme }}
    {{- with .Values.prometheus.monitor.basicAuth }}
      basicAuth: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.prometheus.monitor.bearerTokenFile }}
      bearerTokenFile: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.monitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.prometheus.monitor.proxyUrl }}
      proxyUrl: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.monitor.interval }}
      interval: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.monitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.monitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.prometheus.monitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- range $moduleName, $moduleOptions := .Values.config.modules }}
  {{- if $moduleOptions.enabled }}
    - port: {{ $.Values.service.portName }}
      scheme: {{ $.Values.prometheus.monitor.scheme }}
      path: /probe
      params:
      {{ if ne $moduleName "" }}
        module:
          - {{ $moduleName | quote }}
      {{- end }}
      {{ with $moduleOptions.cache }}
        cache:
          - {{ $moduleOptions.cache | quote }}
      {{- end }}

    {{- with $.Values.prometheus.monitor.basicAuth }}
      basicAuth: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.prometheus.monitor.bearerTokenFile }}
      bearerTokenFile: {{ . }}
    {{- end }}
    {{- with $.Values.prometheus.monitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.prometheus.monitor.proxyUrl }}
      proxyUrl: {{ . }}
    {{- end }}
    {{- with $.Values.prometheus.monitor.interval }}
      interval: {{ . }}
    {{- end }}
    {{- with $.Values.prometheus.monitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
    {{- end }}
    {{- with $.Values.prometheus.monitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.prometheus.monitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
